export type PressItem = {
  id: number
  src: string
  alt: string
  caption: string
  date: string
  url?: string
}

export const PRESS_ITEMS: PressItem[] = [
  {
    id: 1,
    src: "/imgs/prensa1.png",
    alt: "Fanny Torres en entrevista de televisión nacional",
    caption: "Entrevista en Radio Agricultura",
    date: "Fecha",
    url: "https://www.radioagricultura.cl/tendencias/2024/07/19/fanny-torres-silva-revela-como-el-eneagrama-puede-transformar-nuestras-relaciones/",
  },
  {
    id: 2,
    src: "/imgs/prensa2.png",
    alt: "Conferencia magistral en Universidad de Chile",
    caption: "Conferencia magistral en Universidad de Chile",
    date: "Fecha",
  },
  {
    id: 3,
    src: "/imgs/prensa3.png",
    alt: "Artículo en revista Paula",
    caption: "Artículo destacado en Revista Paula",
    date: "Fecha",
  },
  {
    id: 4,
    src: "/imgs/prensa4.png",
    alt: "Participación en programa radial",
    caption: "Entrevista en Radio Cooperativa",
    date: "Fecha",
  },
  {
    id: 5,
    src: "/imgs/prensa5.png",
    alt: "Workshop empresarial",
    caption: "Workshop para ejecutivos en Hotel W",
    date: "Fecha",
  },
  {
    id: 6,
    src: "/imgs/prensa6.png",
    alt: "Lanzamiento de libro",
    caption: "Lanzamiento oficial del libro en Librería Antártica",
    date: "Fecha",
  },
  {
    id: 7,
    src: "/imgs/prensa7.png",
    alt: "Autoconocimiento y relaciones humanas: el Eneagrama como herramienta para conocernos y comprender nuestro rol en la sociedad",
    caption: "Nota en La Hora",
    date: "Fecha",
    url: "https://lahora.cl/estilo-de-vida/2024/07/19/autoconocimiento-y-relaciones-humanas-el-eneagrama-como-herramienta-para-conocernos-y-comprender-nuestro-rol-en-la-sociedad/",
  },
  {
    id: 8,
    src: "/imgs/prensa8.png",
    alt: "Entrevista de Radio: PROGRAMA DESAYUNO DE CAMPEONES",
    caption: "Desayuno de Campeones",
    date: "Fecha",
    url: "https://www.youtube.com/live/iT_lUkJXAmI",
  },
  {
    id: 9,
    src: "/imgs/prensa9.png",
    alt: "La autora chilena Fanny Torres Silva profundiza en el autodescubrimiento con su nuevo libro",
    caption: "Nación Web",
    date: "Fecha",
    url: "https://nacionweb.com.ar/la-autora-chilena-fanny-torres-silva-profundiza-en-el-autodescubrimiento-con-su-nuevo-libro-reconfigurando-el-ser-el-eneagrama-como-mapa-en-tiempos-de-crisis-2/",
  },
  {
    id: 10,
    src: "/imgs/prensa10.png",
    alt: "Revelando los nueve arquetipos del eneagrama: Reconfigurar el ser de Fanny Torres Silva",
    caption: "Corrientes de Tarde",
    date: "Fecha",
    url: "https://corrientesdetarde.com/index.php/bienestar-y-salud/revelando-los-nueve-arquetipos-del-eneagrama-reconfigurar-el-ser-de-fanny-torres-silva-proporciona-una-hoja-de-ruta-para-la-autocomprension-y-la-transformacion/",
  },
  {
    id: 11,
    src: "/imgs/prensa11.png",
    alt: "Entrevista a Fanny Torres Silva en Buenos Aires",
    caption: "Entrevista de televisión en Buenos Aires",
    date: "Fecha",
    url: "https://www.youtube.com/watch?v=FMVyBESKl-Q",
  },
  {
    id: 12,
    src: "/imgs/prensa12.png",
    alt: "Presentación del libro Reconfigurando el Ser en la Feria del Libro de Buenos Aires",
    caption: "Feria Internacional del Libro",
    date: "Fecha",
    url: "https://www.youtube.com/watch?v=WEY7ELHnsrc",
  },
  {
    id: 13,
    src: "/imgs/prensa13.png",
    alt: "La maestra de Eneagrama Fanny Torres Silva presenta su libro Reconfigurando el Ser",
    caption: "Data BA",
    date: "Fecha",
    url: "https://databa.ar/nota/5252/la-maestra-de-eneagrama-fanny-torres-silva-presenta-su-libro-reconfigurando-el-ser/",
  },
  {
    id: 14,
    src: "/imgs/prensa14.png",
    alt: "La maestra de Eneagrama Fanny Torres Silva presenta su libro Reconfigurando el Ser en Buenos Aires",
    caption: "De Queruza",
    date: "Fecha",
    url: "https://dequeruza.ar/la-maestra-de-eneagrama-fanny-torres-silva-presenta-su-libro-reconfigurando-el-ser-el-eneagrama-como-mapa-en-tiempos-de-crisis-en-la-feria-internacional-del-libro-de-buenos-aires/",
  },
  {
    id: 15,
    src: "/imgs/prensa15.png",
    alt: "La maestra de Eneagrama Fanny Torres Silva presenta su libro Reconfigurando el Ser en Buenos Aires",
    caption: "Norte en Línea",
    date: "Fecha",
    url: "https://norteenlinea.com/buenos-aires/la-maestra-de-eneagrama-fanny-torres-silva-presenta-su-libro-reconfigurando-el-ser-el-eneagrama-como-mapa-en-tiempos-de-crisis-en-la-feria-internacional-del-libro-de-buenos-aires",
  },
  {
    id: 16,
    src: "/imgs/prensa16.png",
    alt: "Fanny Torres Silva presentó en Buenos Aires su libro Reconfigurando el Ser",
    caption: "Latam Noticias",
    date: "Fecha",
    url: "https://latamnoticias.com/informacion-general/fanny-torres-silva-presento-en-buenos-aires-su-libro-reconfigurando-el-ser-el-eneagrama-como-mapa-en-tiempos-de-crisis/",
  },
  {
    id: 17,
    src: "/imgs/prensa17.png",
    alt: "Fanny Torres Silva presentó su obra Reconfigurando el Ser en Argentina",
    caption: "La Capital del Sol",
    date: "Fecha",
    url: "https://lacapitaldelsol.com/fanny-torres-silva-presento-su-obra-reconfigurando-el-ser-el-eneagrama-como-mapa-en-tiempos-de-crisis-en-argentina/",
  },
  {
    id: 18,
    src: "/imgs/prensa18.png",
    alt: "Fanny Torres Silva, la maestra de Eneagrama presentó su obra en Buenos Aires",
    caption: "Telenews America",
    date: "Fecha",
    url: "https://www.telenewsamerica.com/2024/05/fanny-torres-silva-la-maestra-de.html",
  },
]
